language: node_js
node_js:
  - 14
braches:
  only:
    - develop
    - master
    - "/^release-[0-999].[0-999].[0-999]$/"
notifications:
  email:
    recipients:
      - hi.rodriguez1998@gmail.com
addons:
  sonarcloud:
    organization: "hugo098" # the key of the org you chose at step #3
    token:
      secure: "qaPIlTU1XlscWaTudlygdLYY95Hdx0DDgeGkrhqyYyy5aVxfPg2vtNh1lx6CnGxCUxMMq5BBPNDuYGbI6lUsY3fGvYxBaAnKe84JehYZIwNzGJ97m943Scyfuta33AdU9vBbXleayt+146vruqS8DfHm0qlKm+mIL18yHvLpg17XRY3wNPVC9XNxXetT9Pr4k8/vRpacZQt6UkpMmtbGvuFf6+gIrZcDw+R0thli2CbaSvTd9JiDMs9GWpBr/Ck62KH/le8j/uX1JDcijqMxg1qMF9+1SWmMroCe0ez0eSR2LxbjlaRR9gOuHdlfPMxGSAJNL5Zw2D75jQwfz1cvVo8fXl963V7h/6+Ou4vuDAkk/y4OtQzHd6VA++1+UOGf78sFSnLZmXETqWvymx17xJyVWBZoLfQWUTOrBmXC1yHLrE8RHEBmQD6NL7wMQlnhJA+GzstOnCnVwfEIkiEiV+wD+ODJwD8sUc98C8h42jXnl6i/PAg7LwFxNkHma52O8MM4lvXiiYljID7pzlZSITnlGX51pPIdP9TeqIMg7lq8rf9TsVqxYkmsWxW3iGFm1HB6/FUZPB5mfd/K5JloynAO64sXFTdpXo8fQ7uvsjQjal33lLQ4XWE1LH/fvcSClx9vbUHcv/S098parxvKaajokrWCmb6Pnr8tVS8ILWQ="
# encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: "EKVV4YvvSy3rTjJ/7s8oH32m1Yxt6lbz/x91xoqD89rVSKeGe/kmuQPXYW/3D9WWeIH+DdZX/5XJY6y0y6vlJ0xvBshDwrMh5QrEz3XtdsGUe9LWACYYbkJzrf2kQvjk6DVI698ppo+CwoHT7dEBbQ+DFr1yYodpTDhlMt8ZV3zzm14i7YwpS7r5llBM3kMWSX+YLxMxXrPebhALnxWzdTtPO/+q9QM00joEHm8hMcWQ59uWpXQ7X6xHlIURoq/dT6I1ufgFANHq5ip5LhKYKSS22M4f0f2XmlpUqHVEJ53bFAxSM+2R8pyWAGl+XdZ8uGoE5Gq+v0vZJI+gLbbNlVAg+Zfmp9U4OBpWCaHj+/rLcmhnrNK5Kz5z1Ce45PMZia6O/AhscAf5duhR/Ilvf+s/KcxBJgJyqdCNbSlCD3TcWC7rBGnq9aIFmIjGaf3rjyYjosKufLz8xxmMf8FFS9QK33F5RLvYXHqOv1A1eGl/B76PC6hPyykb2Zm5m8XuXTR/HPwpX81pNMfGfhmMvTwC+evjngtH9w9TzjvRVTd9qFdtkeeRM7Y7DuqCiiMQWsicQr/7VmOiMGzbEWUUPSItePcjc33LAk9UD0CaFPqBzKG3x0ZlV31eIxfgfZmlZgd72zqV4I/hZ49iV4uwSpw1I09Y583N47AmE0uNsts="
  on:
    branch: master
  app: inventory-hr-api

