import express from 'express';
import logger from 'morgan';
import cookieParser from 'cookie-parser';
import customerRoutes from './routes/customerRoutes.mjs';
export const app = express();
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use('/', customerRoutes);